/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

void add(int aValue, int bValue){
	int result = aValue + bValue;
	printf("Wynik dzialania: %d\n", result);
}

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;

	/*
	 * insert server code here
	 */
	add(argp->x1, argp->x2);
	return &result;
}
