/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"


void
testowy_1(char *host)
{
	CLIENT *clnt;
	wyjscie  *result_1;
	wejscie  obliczenia_1_arg;
	int a, b;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTOWY, PROBNA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Podanie 0 przy obydwu zapytaniach spowoduje wyjscie z aplikacji!\n");
	while(1){
		a = 0; b = 0;
		printf("podaj a > "); scanf("%d", &a);
		printf("\npodaj b > "); scanf("%d", &b);
		if(a == 0 && b == 0){
			printf("\nZakonczono dzialanie klienta.");
			break;
		}
		printf("\nWynik dzialania a+b zostanie wyswietlony w konsoli serwera :)\n\n");
		obliczenia_1_arg.x1 = a; obliczenia_1_arg.x2 = b;
		result_1 = obliczenia_1(&obliczenia_1_arg, clnt);
		if (result_1 == (wyjscie *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	testowy_1 (host);
exit (0);
}
